### ISSUE TITLE
Error codes too long for `flake8>=6.0.0`

### ISSUE THREAD

**Issue by rtb-zla-karma** [python-trio/flake8-async#230]
`flake8` stopped accepting error codes which don't match pattern `^[A-Z]{1,3}[0-9]{0,3}$` in `.flake8` config file under `ignore=` option. Change introduced in this commit https://github.com/PyCQA/flake8/commit/1346ddefd315223b8f476bb02381a944e14f2cbc .

It does work however for `--ignore` command line option (but that basically ignores my `.flake8` config file): 
https://github.com/PyCQA/flake8/issues/1802#issuecomment-1441219096 
> flake8 --ignore=ABCD123 appears to work perfectly

It also works for inline `# noqa` ignores.

Your codes use 5 characters instead of 3. I wanted to
```
ignore =
    #  I have other errors in this file too
    ASYNC900, ASYNC910, ASYNC911
```
But it returns
```
Traceback (most recent call last):
  File "/venv/path/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/venv/path/lib/python3.12/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/venv/path/lib/python3.12/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/venv/path/lib/python3.12/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/venv/path/lib/python3.12/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
                                 ^^^^^^^^^^^^^^^^
  File "/venv/path/lib/python3.12/site-packages/flake8/options/parse_args.py", line 53, in parse_args
    opts = aggregator.aggregate_options(option_manager, cfg, cfg_dir, rest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/path/lib/python3.12/site-packages/flake8/options/aggregator.py", line 30, in aggregate_options
    parsed_config = config.parse_config(manager, cfg, cfg_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/path/lib/python3.12/site-packages/flake8/options/config.py", line 131, in parse_config
    raise ValueError(
ValueError: Error code 'ASYNC900' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
```

Env info
```
Ubuntu 20.04.2 LTS
Python 3.12.2
flake8==7.0.0
flake8-async==24.3.6
```

In `flake8` repo, some Anthony guy who commited the change, behaves like jerk saying basically "it works like it supposed to and stop talking about it" without any consideration for maybe **adding an option to configure this pattern** so that plugin like yours can work:
* https://github.com/PyCQA/flake8/issues/1802#issuecomment-1441220795
* https://github.com/PyCQA/flake8/issues/1777#issuecomment-1367958355
* https://github.com/PyCQA/flake8/issues/1759#issuecomment-1326556905

I don't know if:
1. I'm dumb enough to not be able to find some config option to ignore or change this pattern;
1. I have to use `noqa` in bunch of places;
1. you have to change your error codes;
1. `flake8` must stop enforcing it so rigidly.

Help.

**Comment by jakkdl** [comment]
oh rip. Yeah long error codes has been "officially disallowed" for quite a while, see
https://github.com/python-trio/flake8-async/blob/d29a33d27c3af7b0eb941625b22594fd4629f87a/setup.py#L53-L59

but it's never actually impacted anything before. Given past interactions with them I'm not surprised they don't really care about the impact on plugins, and almost surely won't change back even if it breaks tons of them.

You can work around it currently in a few ways:
1. By using [`--disable`](https://github.com/python-trio/flake8-async?tab=readme-ov-file#--disable) instead of `--ignore` at the moment, since that's a flag that we control.
2. [running it as a standalone](https://github.com/python-trio/flake8-async?tab=readme-ov-file#install-and-run-as-standalone), but that currently doesn't support reading from config files.
3. [Run it through pre-commit](https://github.com/python-trio/flake8-async?tab=readme-ov-file#install-and-run-with-pre-commit), in which case you can configure it with parameters in the `.pre-commit-config.yaml` file.
4. Use the ruff implementation, though they only have some checks implemented and the stable version [splits flake8-async and flake8-trio](https://docs.astral.sh/ruff/rules/#flake8-async-async). See https://github.com/astral-sh/ruff/issues/10303


We could try to work around it by also accepting `ASYxxx` codes in `--disable=`, and do some post-processing to copy over disables to our actual internal codes. Cause surely that

**Comment by jakkdl** [comment]
> It does work however for `--ignore` command line option (but that basically ignores my .flake8 config file)

Oh and another workaround here would be to use `--extend-ignore` on the command line, which wouldn't override `ignore = ...` from the config file.

**Comment by jakkdl** [comment]
I don't think the tryceratops rename is particularly relevant. They renamed because of a conflict with flake8-type-checking and as such didn't really have much of a choice in the matter. I don't want to rename at all, and even if we did change to ASYxxx or w/e it might make more sense to have ruff stick to using ASYNCxxx since it's so much more readable.
We did very recently rename all error codes from TRIOxxx to ASYNCxxx, so it's not entirely unfamiliar territory.

**Comment by Zac-HD** [comment]
Yeah, I think we should probably just document the issue and move on with our lives.

As it happens I do also have PyQCA commit bits, but I really don't have the time and energy to work out what's happened and build a consensus around not-breaking codes which aren't exactly three letters 😥

**Comment by jakkdl** [comment]
Wow the solution in flake8-pylint is... simultaneously hilarious and horrifying: https://github.com/orsinium-labs/flake8-pylint/pull/5
> The PR changes the error codes for all violations by removing the first digit from all codes. So, PLC0114 is replaced with PLC114. _It causes overlaps for some error codes_, but not many. I wish I had a better solution.
