### ISSUE TITLE
New rule: don't `return` inside a nursery, nor `break` or `continue` an outer loop

### ISSUE THREAD

**Issue by Zac-HD** [python-trio/flake8-async#261]
See https://github.com/python-trio/trio/issues/1493 - I'm not sure whether this is a good idea for a lint rule, but wanted to track it so I can decide later.

**Comment by Zac-HD** [comment]
Per https://github.com/python-trio/trio/issues/1493#issuecomment-2277211298, let's do it!

**Comment by jakkdl** [comment]
This also applies to `anyio`, which appears to behave identically to trio regardless of backend.

I don't think it applies to `asyncio`, or at least I'm not able to manifest any counterintuitive behavior. This is largely because you cannot manually cancel their cancelscope-equivalents, and `asyncio.Cancelled` will always be transformed to a `TimeoutError`, so whenever you're losing the return value it's because you're getting an exception thrown in your face.

**Comment by oremanj** [comment]
I think this is still fairly hazardous:
```
async with asyncio.TaskGroup() as tg:
    tg.create_task(do_something_forever())
    await asyncio.sleep(5)
    return "all done!"
```
The return value won't get lost per se, but one does tend to expect a return statement to result in the caller being resumed promptly. Here nothing happens until `do_something_forever()` completes or is cancelled.
